export const UPDATE_PROMPT_IMAGES = 'UPDATE_PROMPT_IMAGES'

export const UPDATE_NEXT_INDEX = 'UPDATE_NEXT_INDEX'

export const UPDATE_PREVIOUS_INDEX = 'UPDATE_PREVIOUS_INDEX'

export const ADD_COMMENT = 'ADD_COMMENT'

export const DELETE_COMMENT = 'DELETE_COMMENT'

export const UPDATE_COMMENT_EDITING = 'UPDATE_COMMENT_EDITING'

export const EDIT_COMMENT = 'EDIT_COMMENT'

export const SET_INITIAL_IMAGES = 'SET_INITIAL_IMAGES'

export const SET_INITIAL_PROMPTS = 'SET_INITIAL_PROMPTS'