export const UPDATE_PROMPT_IMAGES = 'UPDATE_PROMPT_IMAGES'

export const UPDATE_NEXT_INDEX = 'UPDATE_NEXT_INDEX'

export const UPDATE_PREVIOUS_INDEX = 'UPDATE_PREVIOUS_INDEX'

export const ADD_COMMENT = 'ADD_COMMENT'

export const DELETE_COMMENT = 'DELETE_COMMENT'

export const UPDATE_CLASS_NAMES = 'UPDATE_CLASS_NAMES'